api_platform:
  metadata_backward_compatibility_layer: false
  defaults:
    normalization_context:
      skip_null_values: true
  mapping:
    paths: ["%kernel.project_dir%/src/Entity"]
  patch_formats:
    json: ["application/merge-patch+json"]
  swagger:
    api_keys:
      apiKey:
        name: Authorization
        type: header
    versions: [3]
  enable_swagger_ui: false
