vich_uploader:
    db_driver: orm
    metadata:
        type: attribute
    mappings:
        image_object:
            uri_prefix: /images
            upload_destination: '%kernel.project_dir%/public/images'
            # Will rename uploaded files using a uniqueid as a prefix.
            namer: Vich\UploaderBundle\Naming\OrignameNamer